init script implemented

diff --git a/scripts/debian/etc/init.d/echessd b/scripts/debian/etc/init.d/echessd
--- a/scripts/debian/etc/init.d/echessd
+++ b/scripts/debian/etc/init.d/echessd
@@ -21,16 +21,8 @@
 PATH=/sbin:/usr/sbin:/bin:/usr/bin
 DESC="Internet Chess Server"
 NAME=echessd
-DAEMON=/usr/sbin/$NAME
-DAEMON_ARGS="--options args"
 PIDFILE=/var/run/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
-
-# Exit if the package is not installed
-[ -x "$DAEMON" ] || exit 0
-
-# Read configuration variable file if it is present
-[ -r /etc/default/$NAME ] && . /etc/default/$NAME
 
 # Load the VERBOSE setting and other rcS variables
 . /lib/init/vars.sh
@@ -45,18 +37,19 @@ SCRIPTNAME=/etc/init.d/$NAME
 #
 do_start()
 {
-	# Return
-	#   0 if daemon has been started
-	#   1 if daemon was already running
-	#   2 if daemon could not be started
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
-		|| return 1
-	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON -- \
-		$DAEMON_ARGS \
-		|| return 2
-	# Add code here, if necessary, that waits for the process to be ready
-	# to handle requests from services started subsequently which depend
-	# on this one.  As a last resort, sleep for some time.
+    # Return
+    #   0 if daemon has been started
+    #   1 if daemon was already running
+    #   2 if daemon could not be started
+    nohup su --login --command \
+        'erl -sname "echessd" \
+        -mnesia dir \"/var/lib/echessd\" \
+        -echessd_config /etc/echessd.conf \
+        -echessd_privdir /usr/share/echessd \
+        -noshell -noinput \
+        -s mnesia \
+        -s echessd' echessd > /dev/null 2>&1 &
+    return 0
 }
 
 #
@@ -64,38 +57,48 @@ do_start()
 #
 do_stop()
 {
-	# Return
-	#   0 if daemon has been stopped
-	#   1 if daemon was already stopped
-	#   2 if daemon could not be stopped
-	#   other if a failure occurred
-	start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
-	RETVAL="$?"
-	[ "$RETVAL" = 2 ] && return 2
-	# Wait for children to finish too if this is a daemon that forks
-	# and if the daemon is only ever run from this initscript.
-	# If the above conditions are not satisfied then add some other code
-	# that waits for the process to drop all resources that could be
-	# needed by services started subsequently.  A last resort is to
-	# sleep for some time.
-	start-stop-daemon --stop --quiet --oknodo --retry=0/30/KILL/5 --exec $DAEMON
-	[ "$?" = 2 ] && return 2
-	# Many daemons don't delete their pidfiles when they exit.
-	rm -f $PIDFILE
-	return "$RETVAL"
+    # Return
+    #   0 if daemon has been stopped
+    #   1 if daemon was already stopped
+    #   2 if daemon could not be stopped
+    #   other if a failure occurred
+    RANDOM=`date +%N`
+    su --login --command \
+        'erl -sname "echessd_stopper'$RANDOM'" \
+        -noshell -noinput \
+        -s echessd stop_remote' echessd > /dev/null 2>&1
 }
 
 #
 # Function that sends a SIGHUP to the daemon/service
 #
 do_reload() {
-	#
-	# If the daemon can reload its configuration without
-	# restarting (for example, when it is sent a SIGHUP),
-	# then implement that here.
-	#
-	start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE --name $NAME
-	return 0
+    #
+    # If the daemon can reload its configuration without
+    # restarting (for example, when it is sent a SIGHUP),
+    # then implement that here.
+    #
+    RANDOM=`date +%N`
+    su --login --command \
+        'erl -sname "echessd_hupper'$RANDOM'" \
+        -noshell -noinput \
+        -s echessd hup' echessd > /dev/null 2>&1
+    return 0
+}
+
+do_status() {
+    RANDOM=`date +%N`
+    su --login --command \
+        'erl -sname "echessd_pinger'$RANDOM'" \
+        -noshell -noinput \
+        -s echessd ping' echessd > /dev/null 2>&1
+    RET=$?
+    if [ $RET = 0 ]; then
+        echo "$NAME is running." >&2
+    else
+        echo "$NAME is not running." >&2
+    fi
+    return $RET
 }
 
 case "$1" in
@@ -116,18 +119,18 @@ case "$1" in
 	esac
 	;;
   status)
-       status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
+       do_status && exit 0 || exit $?
        ;;
-  #reload|force-reload)
+  reload|force-reload)
 	#
 	# If do_reload() is not implemented then leave this commented out
 	# and leave 'force-reload' as an alias for 'restart'.
 	#
-	#log_daemon_msg "Reloading $DESC" "$NAME"
-	#do_reload
-	#log_end_msg $?
-	#;;
-  restart|force-reload)
+	log_daemon_msg "Reloading $DESC" "$NAME"
+	do_reload
+	log_end_msg $?
+	;;
+  restart)
 	#
 	# If the "reload" option is implemented then remove the
 	# 'force-reload' alias
@@ -150,8 +153,7 @@ case "$1" in
 	esac
 	;;
   *)
-	#echo "Usage: $SCRIPTNAME {start|stop|restart|reload|force-reload}" >&2
-	echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
+	echo "Usage: $SCRIPTNAME {start|stop|restart|reload}" >&2
 	exit 3
 	;;
 esac
